// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {time} from '../models';
import {main} from '../models';

export function DeleteRiskAssessment(arg1:string):Promise<void>;

export function DeleteStockRating(arg1:string):Promise<void>;

export function DeleteTrade(arg1:string):Promise<void>;

export function ExportData(arg1:string):Promise<void>;

export function GetCurrentDirectory():Promise<string>;

export function GetRiskAssessments():Promise<Array<models.RiskAssessment>>;

export function GetStockRatings():Promise<Array<models.StockRating>>;

export function GetStockRatingsByDate(arg1:time.Time):Promise<Array<models.StockRating>>;

export function GetTrades():Promise<Array<models.Trade>>;

export function GetUserDirectory():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportData(arg1:string):Promise<void>;

export function SaveRiskAssessment(arg1:models.RiskAssessment):Promise<void>;

export function SaveStockRating(arg1:models.StockRating):Promise<void>;

export function SaveTrade(arg1:models.Trade):Promise<void>;

export function ShowOpenDialog(arg1:main.DialogOptions):Promise<string>;

export function ShowSaveDialog(arg1:main.DialogOptions):Promise<string>;
