// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {time} from '../models';

export function DeleteRiskAssessment(arg1:string):Promise<void>;

export function DeleteStockRating(arg1:string):Promise<void>;

export function DeleteTrade(arg1:string):Promise<void>;

export function GetLatestMarketRating():Promise<models.StockRating>;

export function GetLatestSectorRating(arg1:string):Promise<models.StockRating>;

export function GetLatestStockRating(arg1:string):Promise<models.StockRating>;

export function GetPositionSettings():Promise<models.PositionSettings>;

export function GetRiskAssessments():Promise<Array<models.RiskAssessment>>;

export function GetStockRatings():Promise<Array<models.StockRating>>;

export function GetStockRatingsByDate(arg1:time.Time):Promise<Array<models.StockRating>>;

export function GetTrades():Promise<Array<models.Trade>>;

export function Greet(arg1:string):Promise<string>;

export function RunDatabaseMaintenance():Promise<string>;

export function SavePositionSettings(arg1:models.PositionSettings):Promise<void>;

export function SaveRiskAssessment(arg1:models.RiskAssessment):Promise<void>;

export function SaveStockRating(arg1:models.StockRating):Promise<void>;

export function SaveTrade(arg1:models.Trade):Promise<void>;
