// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteRiskAssessment(arg1) {
  return window['go']['main']['App']['DeleteRiskAssessment'](arg1);
}

export function DeleteStockRating(arg1) {
  return window['go']['main']['App']['DeleteStockRating'](arg1);
}

export function DeleteTrade(arg1) {
  return window['go']['main']['App']['DeleteTrade'](arg1);
}

export function GetLatestMarketRating() {
  return window['go']['main']['App']['GetLatestMarketRating']();
}

export function GetLatestSectorRating(arg1) {
  return window['go']['main']['App']['GetLatestSectorRating'](arg1);
}

export function GetLatestStockRating(arg1) {
  return window['go']['main']['App']['GetLatestStockRating'](arg1);
}

export function GetPositionSettings() {
  return window['go']['main']['App']['GetPositionSettings']();
}

export function GetRiskAssessments() {
  return window['go']['main']['App']['GetRiskAssessments']();
}

export function GetStockRatings() {
  return window['go']['main']['App']['GetStockRatings']();
}

export function GetStockRatingsByDate(arg1) {
  return window['go']['main']['App']['GetStockRatingsByDate'](arg1);
}

export function GetTrades() {
  return window['go']['main']['App']['GetTrades']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RunDatabaseMaintenance() {
  return window['go']['main']['App']['RunDatabaseMaintenance']();
}

export function SavePositionSettings(arg1) {
  return window['go']['main']['App']['SavePositionSettings'](arg1);
}

export function SaveRiskAssessment(arg1) {
  return window['go']['main']['App']['SaveRiskAssessment'](arg1);
}

export function SaveStockRating(arg1) {
  return window['go']['main']['App']['SaveStockRating'](arg1);
}

export function SaveTrade(arg1) {
  return window['go']['main']['App']['SaveTrade'](arg1);
}
